会場を株式会社インプレスに変更
Dtakeuchi818/ichiyasaGitSample pull request #1
Opened 2023-12-01 11:57 UTC by Dtakeuchi818

### 変更内容
会場を「株式会社インプレス」に変更しました

### 背景
ご厚意です

2023-12-01 12:06 UTC, dTakeuchiGU commented
問題ないと思います！マージします

2023-12-01 12:13 UTC, dTakeuchiGU requested changes
ありがとうございます！
指摘した点だけ修正してください。

2023-12-01 12:13 UTC, dTakeuchiGU commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
株式会社いらないと思います。

2023-12-01 12:17 UTC, Dtakeuchi818 commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
修正したものをpusuしました。

2023-12-01 12:18 UTC, dTakeuchiGU commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
ありがとうございます！！

2023-12-01 12:19 UTC, dTakeuchiGU approved these changes

2023-12-03 04:30 UTC, dTakeuchiGU requested changes
訂正します。
やっぱりコメントのように修正お願いします。

2023-12-03 04:30 UTC, dTakeuchiGU commented on index.html
> +                        <p>インプレス イベントセミナー会場</p>
### 訂正
やっぱり**株式会社**いるかもしれないです。

2023-12-03 04:40 UTC, Dtakeuchi818 commented on index.html
> +                        <p>インプレス イベントセミナー会場</p>
修正したものをpushしました。
ご確認お願いします。

2023-12-03 04:44 UTC, dTakeuchiGU commented
ありがとうございます！
問題ないのでマージします。

2023-12-03 04:45 UTC, dTakeuchiGU commented on index.html
> +                        <p>インプレス イベントセミナー会場</p>
ありがとうございます

2023-12-03 04:45 UTC, dTakeuchiGU approved these changes

2023-12-03 04:46 UTC, dTakeuchiGU commented on index.html
> +                        <p>インプレス イベントセミナー会場</p>
👍

2023-12-03 04:48 UTC, merged